apiVersion: apps/v1
kind: Deployment # what kind of object you want to create, [Deployment,Service,Replica Set,Replication Controller, StateFulSets,DaemonSet,...]
metadata:
  name: echo-server-deployment
  labels: ## labels 没什么特别意义
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: walkerliu/echo-server-example
          ports:
            - containerPort: 8888 # use 8888 as expose port