apiVersion: apps/v1
kind: Deployment # what kind of object you want to create, [Deployment,Service,Replica Set,Replication Controller, StateFulSets,DaemonSet,...]
metadata:
  name: http-server-deployment
  labels: ## labels 没什么特别意义
    app: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: walkerliu/http-server-example
          imagePullPolicy: Always
          ports:
            - containerPort: 8888 # use 8888 as expose port
      schedulerName: default-scheduler