apiVersion: apps/v1
kind: Deployment # what kind of object you want to create, [Deployment,Service,Replica Set,Replication Controller, StateFulSets,DaemonSet,...]
metadata:
  name: service-discovery-example-deployment
  labels: ## labels 没什么特别意义
    app: service-discovery-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery-example
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-discovery-example
    spec:
      containers:
        - name: service-discovery-example
          image: walkerliu/service-discovery-example
          imagePullPolicy: Always
      schedulerName: default-scheduler